### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by FedericoGiovannacci** [CarlosCrisonG/mercadoliebre#1]
- [Parte 1] - Cumple
- [Parte 2] - Cumple
- [Parte 3] - Cumple, quizás se podría ajustar que en _mobile_ y _tablet_ al hacer el hover sobre el producto no se solape la descripción con el producto de abajo.
- [Parte 4] - Cumple
- [Parte 5] - Cumple
- [Parte 6] - Cumple
- [Parte 7] - Cumple
- [Parte 8] - Cumple
- [Parte 9] - Cumple
- [Parte 10] - Cumple

Felicitaciones!

**Comment by CarlosCrisonG** [comment]
Todo listo. Issue corregido. Gracias !
