### ISSUE TITLE
Mejoras en el header

### ISSUE THREAD

**Issue by JaiderValencia** [CarlosCrisonG/mercadoliebre#2]
- La tipografía del texto que dice "Comprá en cuotas y sin tarjeta de crédito" está pequeña en las vistas de tablet y desktop.
    ![image](https://user-images.githubusercontent.com/53984281/220496048-29f9fd29-5fe2-4445-b736-33f26667bc5c.png)

- El ícono de la lupa en la barra de búsqueda desaparece en tablet y en mobile.
   ![image](https://user-images.githubusercontent.com/53984281/220496387-e69a9985-e6df-4533-b24f-b9f3496d158e.png)

**Comment by CarlosCrisonG** [comment]
Todo listo. Issue corregido. Gracias  :)
