### ISSUE TITLE
Mejoras en el main

### ISSUE THREAD

**Issue by JaiderValencia** [CarlosCrisonG/mercadoliebre#3]
- [ ] El home banner podría ocupar el 100% del ancho del body.

![image](https://user-images.githubusercontent.com/53984281/220497216-0bc945f1-f250-4592-bffa-d0918aef55ac.png)

- [ ] El descuento de las dos tarjetas del centro no se ven bien en la vista de desktop.

![image](https://user-images.githubusercontent.com/53984281/220497782-8032c0a4-202e-453a-865d-9da3b6556157.png)

- [ ]  Al hacer el hover en las tarjetas de los productos en la vista de tablet, la información no se ve deja ver bien. 
 
![image](https://user-images.githubusercontent.com/53984281/220498385-241a81ba-814e-45f9-8225-292b4f35eae1.png)

**Comment by CarlosCrisonG** [comment]
Perfecto, todo corregido. Gracias.
